timeout 30

default mmc-rootfs

menu title etinker [k3-j721e-sk] Boot Options:

label mmc-rootfs
	kernel /Image
	fdt /dtb/ti/k3-j721e-sk.dtb
	fdtoverlays /dtb/ti/k3-j721e-sk-etinker.dtbo
	append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 mtdparts=47040000.spi.0:512k(ospi.tiboot3),2m(ospi.tispl),4m(ospi.u-boot),256k(ospi.env),1m(ospi.sysfw),256k(ospi.env.backup),57344k@8m(ospi.rootfs),256k(ospi.phypattern);47034000.hyperbus:512k(hbmc.tiboot3),2m(hbmc.tispl),4m(hbmc.u-boot),256k(hbmc.env),1m(hbmc.sysfw),-@8m(hbmc.rootfs) root=/dev/mmcblk1p2 rw rootfstype=ext4 rootwait
