#!/bin/bash
#
# This script ONLY used when bumping the U-Boot versions
#

usage ()
{
	printf "\nusage: bootloader-bump <command>\n\n"
	printf "<command>\n"
	printf "\tbuild   - Purge and Build\n"
	printf "\tupdate  - Clean and Build\n"
	printf "\t*config - {g,menu,n,old}config\n\n"
}

do_make ()
{
	case $1 in
	*config)
		ET_BOARD=$2 make bootloader-$1
		;;
	update)
		ET_BOARD=$2 make bootloader-$1
		;;
	build)
		ET_BOARD=$2 make bootloader-purge bootloader
		;;
	*)
		;;
	esac
}

is_virtual ()
{
	if [ "`grep -Po -e 'is virtual' boards/$1/etinker.mk 2> /dev/null`" = "is virtual" ]; then
		return 0
	else
		return 1
	fi
}

# verify first positional argument
if [ -e $1 ]; then
	printf "Missing arguments!\n"
	usage
	exit 1
fi

# validate first positional argument
case $1 in
*config | update | build)
	;;
*)
	printf "Invalid argument list!\n"
	usage
	exit 1
	;;
esac

# check state of boards directory
for n in `ls boards`; do
	if ! [ -f boards/$n/etinker.mk ]; then
		printf "'$n' is not a valid etinker board!\n" $n
		exit 1
	fi
done

# operate on valid virtual boards
for n in `ls boards`; do
	if ! is_virtual $n; then
		continue
	fi

	# select boards with U-Boot config
	for b in `ls boards/$n/config/`; do
		case $b in
		u-boot-*)
			board=`echo $b | grep -Po 'u-boot-\K[^\n]*'`
			if ! do_make $1 $board; then
				printf "etinker $0 failed!\n"
				exit 1
			fi
			;;
		*)
			;;
		esac

	done
done
