#!/bin/bash
#
# This script ONLY used when bumping the Linux versions
#

ET_DIR="`realpath -e $(dirname $0)/..`"

usage ()
{
	printf "\nusage: kernel-bump <command> [-rt]\n\n"
	printf "<command>\n"
	printf "\tmake <target> - Direct make target\n"
	printf "\tbuild         - Purge and Build\n"
	printf "\tupdate        - Clean and Build\n"
	printf "\t*config       - {g,menu,n,old}config\n\n"
}

do_make ()
{
	printf "\n[$1]\n"
	case $2 in
	make)
		ET_BOARD=$1 make kernel-$3
		;;
	*config)
		ET_BOARD=$1 make kernel-$2
		;;
	update)
		ET_BOARD=$1 make kernel-$2 overlay-$2
		;;
	build)
		ET_BOARD=$1 make kernel-purge overlay-update
		;;
	*)
		;;
	esac
}

is_virtual ()
{
	if [ "`grep -Po -e 'is virtual' ${ET_DIR}/boards/$1/etinker.mk 2> /dev/null`" = "is virtual" ]; then
		return 0
	else
		return 1
	fi
}

is_rt ()
{
	for param in $@; do
		if [ "$param" = "-rt" ]; then
			return 0
		fi
	done
	return 1
}

# verify first positional argument
if [ -e $1 ]; then
	printf "Missing arguments!\n"
	usage
	exit 1
fi

# validate first positional argument
case $1 in
make)
	if [ -e $2 ]; then
		printf "Missing 'make' arguments!\n"
		usage
		exit 1
	fi
	;;
*config | update | build)
	;;
*)
	printf "Invalid argument list!\n"
	usage
	exit 1
	;;
esac

# check state of boards directory
for n in `ls ${ET_DIR}/boards`; do
	if ! [ -f ${ET_DIR}/boards/$n/etinker.mk ]; then
		printf "'$n' is not a valid etinker board!\n" $n
		exit 1
	fi
	if is_virtual $n; then
		continue
	fi
done

# operate on valid boards
for n in `ls ${ET_DIR}/boards`; do
	if is_virtual $n; then
		continue
	fi

	# realtime boards
	if is_rt "$@"; then
		case $n in
		aml-s905x-cc-rt | ls1043ardb-rt | omap3-evm-rt)
			if ! do_make $n "$@"; then
				printf "etinker $0 failed!\n"
				exit 1
			fi
			;;
		*)
			;;
		esac
		continue
	fi

	# baseline boards
	case $n in
	am335x-pocketbeagle | aml-s905x-cc | ls1012afrdm | ls1043ardb | pynq-z2-xlnx | pynq-z2 | sama5d3-xpld)
		if ! do_make $n "$@"; then
			printf "etinker $0 failed!\n"
			exit 1
		fi
		;;
	*)
		;;
	esac
done
