#!/bin/bash
#
# This script ONLY used when bumping the Buildroot versions
#

usage ()
{
	printf "\nusage: rootfs-bump <command>\n\n"
	printf "<command>\n"
	printf "\tmake <target> - Direct make target\n"
	printf "\tbuild         - Purge and Build\n"
	printf "\tupdate        - Clean and Build\n"
	printf "\t*config       - {g,menu,n,old}config\n\n"
}

do_make ()
{
	printf "\n[$1]\n"
	case $2 in
	*config | make)
		ET_BOARD=$1 make rootfs-$3
		;;
	update)
		ET_BOARD=$1 make rootfs-$2 kernel-$2 overlay-$2
		;;
	build)
		ET_BOARD=$1 make rootfs-purge rootfs kernel-update overlay-update
		;;
	*)
		;;
	esac
}

is_virtual ()
{
	if [ "`grep -Po -e 'is virtual' boards/$1/etinker.mk 2> /dev/null`" = "is virtual" ]; then
		return 0
	else
		return 1
	fi
}

# verify first positional argument
if [ -e $1 ]; then
	printf "Missing arguments!\n"
	usage
	exit 1
fi

# validate first positional argument
case $1 in
make)
	if [ -e $2 ]; then
		printf "Missing 'make' arguments!\n"
		usage
		exit 1
	fi
	;;
*config | update | build)
	;;
*)
	printf "Invalid argument list!\n"
	usage
	exit 1
	;;
esac

# check state of boards directory
for n in `ls boards`; do
	if ! [ -f boards/$n/etinker.mk ]; then
		printf "'$n' is not a valid etinker board!\n" $n
		exit 1
	fi
done

# operate on valid boards
for n in `ls boards`; do
	if is_virtual $n; then
		continue
	fi

	# boards with a Linux root filesystem
	case $n in
	am335x-pocketbeagle* | aml-s905x-cc* | ls1043ardb* | pynq-z2* | sama5d3-xpld*)
		if ! do_make $n "$@"; then
			printf "etinker $0 failed!\n"
			exit 1
		fi
		;;
	*)
		;;
	esac
done
