#!/bin/bash
#

usage ()
{
	printf "\nusage: sandbox <command>\n\n"
	printf "<command>\n"
	printf "\tmake <targets> - Build specified Linux board targets\n"
	printf "\tbuild          - Build all Linux boards\n"
	printf "\tinfo           - Show build variables for all Linux boards\n"
	printf "\tupdate         - Clean and build all Linux boards\n"
	printf "\tversion        - Show version information for all Linux boards\n\n"
}

do_make ()
{
	printf "\n[$1]\n"
	case $2 in
	make)
		args="`echo $@ | cut -d ' ' -f 3-9`"
		ET_BOARD=$1 make $args
		;;
	info | update | version)
		ET_BOARD=$1 make $2
		;;
	build)
		ET_BOARD=$1 make sandbox
		;;
	*)
		;;
	esac
}

is_virtual ()
{
	if [ "`grep -oe 'is virtual' boards/$1/etinker.mk 2> /dev/null`" = "is virtual" ]; then
		return 0
	else
		return 1
	fi
}

# verify first positional argumement
if [ -z "$1" ]; then
	printf "Missing arguments!\n"
	usage
	exit 1
fi

# validate first positional argumement
case $1 in
make)
	if [ -e $2 ]; then
		printf "Missing 'make' arguments!\n"
		usage
		exit 1
	fi
	;;
info | update | version)
	;;
*)
	printf "Invalid argument list!\n"
	usage
	exit 1
	;;
esac

# check state of boards directory
for n in `ls boards`; do
	if ! [ -f boards/$n/etinker.mk ]; then
		printf "'$n' is not a valid etinker board!\n" $n
		exit 1
	fi
	if is_virtual $n; then
		continue
	fi
done

# operate on valid boards
for n in `ls boards`; do
	if is_virtual $n; then
		continue
	fi

	# baseline boards
	case $n in
	aml-s905x-cc* | am335x-* | ls1012afrdm* | ls1043ardb* | pynq-z2* | sama5d3-xpld*)
		if ! do_make $n "$@"; then
			printf "etinker $0 failed!\n"
			exit 1
		fi
		;;
	*)
		;;
	esac
done
