#!/bin/bash
#

usage ()
{
	printf "\nusage: sandbox <command> [-rt]\n\n"
	printf "<command>\n"
	printf "\tupdate  - Clean and Build\n\n"
}

do_make ()
{
	case $1 in
	update)
		ET_BOARD=$2 make update
		;;
	*)
		;;
	esac
}

is_virtual ()
{
	if [ "`grep -Po -e 'is virtual' boards/$1/etinker.mk 2> /dev/null`" = "is virtual" ]; then
		return 0
	else
		return 1
	fi
}

# verify first positional argumement
if [ -e $1 ]; then
	printf "Missing arguments!\n"
	usage
	exit 1
fi

# validate first positional argumement
case $1 in
update)
	;;
*)
	printf "Invalid argument list!\n"
	usage
	exit 1
	;;
esac

# check state of boards directory
for n in `ls boards`; do
	if ! [ -f boards/$n/etinker.mk ]; then
		printf "'$n' is not a valid etinker board!\n" $n
		exit 1
	fi
	if is_virtual $n; then
		continue
	fi
done

# operate on valid boards
for n in `ls boards`; do
	if is_virtual $n; then
		continue
	fi

	# baseline boards
	case $n in
	aml-s905x-cc* | ls1043ardb* | am335x-pocketbeagle | sama5d3-xpld | pynq-z2*)
		if ! do_make $1 $n; then
			printf "etinker $0 failed!\n"
			exit 1
		fi
		;;
	*)
		;;
	esac
done
