#!/usr/bin/env bash

if which apt &> /dev/null; then
	sudo apt update
	if ! [ "$?" = "0" ];then
		printf "APT Update Error!\n"
		exit 1
	fi
	sudo apt full-upgrade -y
	if ! [ "$?" = "0" ];then
		printf "APT Full Upgrade Error!\n"
		exit 1
	fi

	# crosstool-ng
	# - https://github.com/crosstool-ng/crosstool-ng/blob/master/testing/docker/ubuntu22.04/Dockerfile
	sudo apt install -y \
		autoconf \
		automake \
		bison \
		bzip2 \
		flex \
		g++ \
		gawk \
		gcc \
		git \
		gperf \
		help2man \
		libncurses5-dev \
		libstdc++6 \
		libtool-bin \
		libtool \
		make \
		meson \
		ninja-build \
		patch \
		python3-dev \
		rsync \
		texinfo \
		unzip \
		wget \
		xz-utils

	if ! [ "$?" = "0" ]; then
		printf "APT Install Error! [ crosstool-ng ]\n"
		exit 1
	fi

	# buildroot
	# - https://buildroot.org/downloads/manual/manual.html#requirement
	sudo apt install -y \
		bash \
		bc \
		binutils \
		build-essential \
		cmake \
		cpio \
		curl \
		cvs \
		dblatex \
		default-jdk-headless \
		diffutils \
		file \
		findutils \
		g++-multilib \
		gcc-multilib \
		graphviz \
		gzip \
		lib32stdc++6 \
		lib32z1 \
		libc6-i386 \
		libgmp-dev \
		libglib2.0-dev \
		libgtk-3-dev \
		libmpc-dev \
		libpython3-all-dev \
		libsecret-1-dev \
		libssl-dev \
		libxss-dev \
		mercurial \
		perl \
		python3-aiohttp \
		python3-matplotlib \
		rsync \
		sed \
		subversion \
		tar \
		u-boot-tools \
		w3m \
		which

	if ! [ "$?" = "0" ]; then
		printf "APT Install Error! [ buildroot ]\n"
		exit 1
	fi

	# generally required
	sudo apt install -y \
		libc-dev-bin \
		libdebuginfod-dev \
		python3-all-dev \
		python3-argparse-addons \
		python3-cryptography \
		python3-deprecated \
		python3-deprecation \
		python3-pyelftools \
		python3-jsonschema \
		python3-jsonschema-specifications \
		python3-pip \
		python3-setuptools \
		python3-virtualenv \
		python3-yaml \
		python-is-python3 \
		x11-utils \
		yamllint

	if ! [ "$?" = "0" ]; then
		printf "APT Install Error! [ general ]\n"
		exit 1
	fi

	if [ -n "$1" ] && [ "$1" = "dev" ]; then
		# etinker
		sudo apt install -y \
			ccache \
			chrpath \
			cifs-utils \
			debootstrap \
			default-jdk \
			device-tree-compiler \
			dialog \
			diffstat \
			docbook-utils \
			docbook2x \
			dos2unix \
			dosfstools \
			exuberant-ctags \
			fakeroot \
			flip \
			gcc-doc \
			gettext \
			git-email \
			gitg \
			gitk \
			gnupg \
			indent \
			inkscape \
			intltool \
			iproute2 \
			less \
			libasound2-dev \
			libelf-dev \
			libexpat1-dev \
			libfreetype-dev \
			libgpiod-dev \
			libgnutls28-dev \
			libhidapi-dev \
			libiberty-dev \
			libinput-dev \
			libjpeg-dev \
			liblua5.1-0-dev \
			liblua5.2-dev \
			liblua5.3-dev \
			liblua5.4-dev \
			libluajit-5.1-dev \
			libncurses-dev \
			libnuma-dev \
			libreadline-dev \
			libsdl2-dev \
			libsdl2-gfx-dev \
			libsdl2-image-dev \
			libsdl2-mixer-dev \
			libsdl2-net-dev \
			libsdl2-ttf-dev \
			libselinux1 \
			libtracecmd-dev \
			libtraceevent-dev \
			libtracefs-dev \
			libusb-1.0-0-dev \
			libx11-dev \
			libxext-dev \
			libxml2-dev \
			libxml2-utils \
			libzstd-dev \
			lrzsz \
			lua5.1 \
			lua5.2 \
			lua5.3 \
			lua5.4 \
			luajit \
			lzma \
			lzop \
			man-db \
			manpages-dev \
			manpages-posix-dev \
			mc \
			moreutils \
			mtd-utils \
			mtools \
			netpbm \
			net-tools \
			openssh-client \
			openssh-server \
			pahole \
			patchelf \
			pax \
			pkg-config \
			rlwrap \
			rpm \
			schroot \
			screen \
			snap \
			snapd \
			socat \
			sshfs \
			stow \
			sudo \
			swig \
			tcl \
			texinfo \
			tig \
			tmux \
			tofrodos \
			tree \
			trace-cmd \
			uucp \
			uuid-dev \
			vim \
			whiptail \
			whois \
			xmlto \
			xvfb \
			zip \
			zlib1g-dev

		if ! [ "$?" = "0" ]; then
			printf "APT Install Error! [ dev ]\n"
			exit 1
		fi
	fi

	# Clean local package cache
	sudo apt clean

	# Cleanup dangling packages
	sudo apt autoremove
fi

is_arch="$(grep -q Arch /etc/os-release && printf ok)"
is_artix="$(grep -q Artix /etc/os-release && printf ok)"
if which pacman &> /dev/null && [ -n "${is_arch}" ] || [ -n "${is_artix}" ]; then
	sudo pacman -Syu --quiet --color auto --noprogressbar --needed --noconfirm
	if ! [ "$?" = "0" ]; then
		printf "Upgrade Error!\n"
		exit 1
	fi
	if which yay &> /dev/null; then
		yay --answerdiff None --answerclean None --noremovemake --noconfirm -Syu
	fi

	# crosstool-ng
	# - https://github.com/crosstool-ng/crosstool-ng/blob/master/testing/docker/ubuntu22.04/Dockerfile
	sudo pacman -S --quiet --color auto --noprogressbar --needed --noconfirm \
		autoconf \
		automake \
		bison \
		bzip2 \
		flex \
		gawk \
		gcc \
		git \
		gperf \
		help2man \
		ncurses \
		libstdc++ \
		libtool \
		make \
		meson \
		ninja \
		patch \
		python \
		rsync \
		texinfo \
		unzip \
		wget \
		xz

	if ! [ "$?" = "0" ]; then
		printf "pacman Install Error! [ crosstool-ng ]\n"
		exit 1
	fi

	# buildroot
	# - https://buildroot.org/downloads/manual/manual.html#requirement
	sudo pacman -S --quiet --color auto --noprogressbar --needed --noconfirm \
		alsa-lib \
		bash \
		bc \
		binutils \
		cmake \
		cpio \
		curl \
		cvs \
		dblatex \
		diffutils \
		file \
		findutils \
		graphviz \
		gptfdisk \
		gzip \
		jdk25-openjdk \
		gmp \
		glib2-devel \
		gtk3 \
		gtk4 \
		libsecret \
		libxss \
		mpc \
		openssl \
		mercurial \
		multilib-devel \
		perl \
		python-aiohttp \
		python-matplotlib \
		sed \
		subversion \
		tar \
		uboot-tools \
		w3m \
		which

	if ! [ "$?" = "0" ]; then
		printf "pacman Install Error! [ buildroot ]\n"
		exit 1
	fi

	# generally required
	sudo pacman -S --quiet --color auto --noprogressbar --needed --noconfirm \
		debuginfod \
		python-argparse-manpage \
		python-build \
		python-cryptography \
		python-deprecated \
		python-deprecation \
		python-installer \
		python-pyelftools \
		python-jsonschema \
		python-jsonschema-specifications \
		python-pip \
		python-setuptools \
		python-uv \
		python-virtualenv \
		python-yaml \
		rpcsvc-proto \
		xorg-xlsclients \
		yamllint

	if ! [ "$?" = "0" ]; then
		printf "pacman Install Error! [ general ]\n"
		exit 1
	fi

	if [ -n "$1" ] && [ "$1" = "dev" ]; then
		# etinker
		sudo pacman -S --quiet --color auto --noprogressbar --needed --noconfirm \
			ccache \
			chrpath \
			cifs-utils \
			ctags \
			debootstrap \
			dialog \
			diffstat \
			docbook-utils \
			docbook2x \
			dos2unix \
			dosfstools \
			dtc \
			expat \
			fakeroot \
			flip-link \
			freetype2 \
			gettext \
			gitg \
			gnupg \
			gnutls \
			gvim \
			hidapi \
			indent \
			inkscape \
			intltool \
			iproute2 \
			less \
			libelf \
			libgpiod \
			libinput \
			libjpeg-turbo \
			libusb \
			libx11 \
			libxext \
			libxml2 \
			lrzsz \
			lua51 \
			lua52 \
			lua53 \
			lua54 \
			luajit \
			lzop \
			man-db \
			man-pages \
			man-pages-utils \
			mc \
			moreutils \
			mtd-utils \
			mtools \
			netpbm \
			net-tools \
			numa \
			numactl \
			openssh \
			pahole \
			patchelf \
			pax \
			pkgconf \
			readline \
			rlwrap \
			rpm-tools \
			schroot \
			screen \
			sdl2_gfx \
			sdl2_image \
			sdl2_mixer \
			sdl2_net \
			sdl2_ttf \
			socat \
			sshfs \
			stow \
			sudo \
			swig \
			tcl \
			texinfo \
			tig \
			tk \
			tmux \
			tree \
			trace-cmd \
			uucp \
			whois \
			xmlto \
			xorg-server-xvfb \
			zip \
			zlib-ng \
			zlib \
			zstd

		if ! [ "$?" = "0" ]; then
			printf "pacman Install Error! [ dev ]\n"
			exit 1
		fi
	fi

	# ccache fixup
	if ! [ -L "/usr/lib/ccache/cc" ] && [ -L "/usr/lib/ccache/bin/cc" ]; then
		for f in `ls "/usr/lib/ccache/bin/"`; do
			(cd "/usr/lib/ccache" && sudo ln -sf bin/$f)
		done
	fi
fi

# Python3 packages
pip3 install asciidoc --break-system-packages

# We like 'bash'
$(ls -l /bin/sh | grep -q bash) || (cd /bin && sudo ln -sf bash sh && ls -l sh)
