#!/bin/bash

TARGET=$1

printf "\n***** [${ET_BOARD}][${ET_BOARD_TYPE}] post-build script *****\n\n"

# Preserve target directory
cp -a ${TARGET} ${TARGET}-bare

# Update target file system
mkdir -p ${TARGET}/lib/firmware
rsync -av ${ET_DIR}/common/rootfs/* ${TARGET}/ 2>/dev/null
if [ -d ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib ]; then
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libssp.so* ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libSegFault.so ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libmemusage.so ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libpcprofile.so ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libitm.so* ${TARGET}/lib/ 2>/dev/null
fi
if [ -d ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/debug-root ]; then
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/debug-root/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_KERNEL_DIR}/boot ]; then
	rsync -av ${ET_KERNEL_DIR}/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_BOOTLOADER_DIR}/boot ]; then
	rsync -av ${ET_BOOTLOADER_DIR}/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_OVERLAY_DIR} ]; then
	rsync -av \
		--exclude 'usr/include' \
		--exclude 'usr/lib/pkgconfig' \
		--exclude 'usr/lib/*.a' \
		${ET_OVERLAY_DIR}/ \
		${TARGET}/ 2>/dev/null
fi
printf "\n%s\n\n" "`cat ${TARGET}/etc/issue`" > ${TARGET}/etc/issue
printf "\n::sysinit:/bin/mount -t debugfs none /sys/kernel/debug\n" >> ${TARGET}/etc/inittab
printf "\n::sysinit:/bin/mount -t configfs none /sys/kernel/config\n" >> ${TARGET}/etc/inittab
sed -i s,::sysinit:/etc/init.d/rcS,#::sysinit:/etc/init.d/rcS, ${TARGET}/etc/inittab
printf "\n::sysinit:/etc/init.d/rcS\n" >> ${TARGET}/etc/inittab
printf "\n#ttyGS0::respawn:/sbin/getty -L ttyGS0 115200 vt102\n" >> ${TARGET}/etc/inittab

# Board Specific Modifications
case "${ET_BOARD_TYPE}" in
omap2plus|sama5d3-xpld*|zynq*|meson*)
	printf "\n***** [${ET_BOARD}][${ET_BOARD_TYPE}] update /etc/fstab *****\n\n"
	mkdir -p ${TARGET}/media/BOOT
	mkdir -p ${TARGET}/media/rootfs
	sed -i s,ext2,ext4, ${TARGET}/etc/fstab
	echo "${ET_BOARD_TYPE}" | grep -q "meson"
	if [ "$?" = "0" ]; then
		printf "/dev/mmcblk1p1 /media/BOOT auto defaults 0 0\n" >> ${TARGET}/etc/fstab
		printf "/dev/mmcblk1p2 /media/rootfs auto defaults 0 0\n" >> ${TARGET}/etc/fstab
	else
		printf "/dev/mmcblk0p1 /media/BOOT auto defaults 0 0\n" >> ${TARGET}/etc/fstab
		printf "/dev/mmcblk0p2 /media/rootfs auto defaults 0 0\n" >> ${TARGET}/etc/fstab
	fi
	case "${ET_BOARD}" in
	omap3-beagle-xm*|am335x-pocketbeagle*|sama5d3-xpld*)
		case "${ET_BOARD}" in
		am335x*)
			# ADD FIRMWARE
			rsync -av ${ET_DIR}/firmware/am335x* ${TARGET}/lib/firmware/
			;;
		*)
			# DEFAULT NO-OP
			;;
		esac
		;;
	*)
		# NAND AVAILABLE
		mkdir -p ${TARGET}/media/ubifs
		printf "ubi0:rootfs /media/ubifs ubifs defaults 0 0\n" >> ${TARGET}/etc/fstab
		;;
	esac
	;;
*)
	# DEFAULT NO-OP
	;;
esac
