#!/bin/bash

TARGET=$1

printf "\n***** [${ET_BOARD}][${ET_BOARD_TYPE}] post-build script *****\n\n"

# Preserve target directory
cp -a ${TARGET} ${TARGET}-bare

# Update target file system
rsync -av ${ET_DIR}/common/rootfs/* ${TARGET}/ 2>/dev/null
if [ -d ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/debug-root ]; then
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/debug-root/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_KERNEL_DIR}/boot ]; then
	rsync -av ${ET_KERNEL_DIR}/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_BOOTLOADER_DIR}/boot ]; then
	rsync -av ${ET_BOOTLOADER_DIR}/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_OVERLAY_DIR} ]; then
	rsync -av \
		--exclude 'usr/include' \
		--exclude 'usr/lib/pkgconfig' \
		--exclude 'usr/lib/*.a' \
		${ET_OVERLAY_DIR}/ \
		${TARGET}/ 2>/dev/null
	${TARGET}/usr/lib/*.a 2>/dev/null
fi
printf "\n%s\n\n" "`cat ${TARGET}/etc/issue`" > ${TARGET}/etc/issue
printf "\n::sysinit:/bin/mount -t debugfs none /sys/kernel/debug\n" >> ${TARGET}/etc/inittab

# Board Specific Modifications
case "${ET_BOARD_TYPE}" in
	omap2plus|sama5d3-xpld-*)
		printf "\n***** [${ET_BOARD}][${ET_BOARD_TYPE}] update /etc/fstab *****\n\n"
		mkdir -p ${TARGET}/media/BOOT
		mkdir -p ${TARGET}/media/rootfs
		printf "/dev/mmcblk0p1 /media/BOOT auto defaults 0 0\n" >> ${TARGET}/etc/fstab
		printf "/dev/mmcblk0p2 /media/rootfs auto defaults 0 0\n" >> ${TARGET}/etc/fstab
		case "${ET_BOARD}" in
			*omap3-evm*|*beagle*|sama5d3-xpld-*)
				mkdir -p ${TARGET}/media/ubifs
				printf "ubi0:rootfs /media/ubifs ubifs defaults 0 0\n" >> ${TARGET}/etc/fstab
				;;
			*)
				;;
		esac
		;;
	*)
		;;
esac
