#!/bin/bash

TARGET=$1

printf "\n***** [${ET_BOARD}][${ET_BOARD_TYPE}] post-build script *****\n\n"

# Preserve target directory
if [ -d ${TARGET}-bare ]; then
	printf "***** [${ET_BOARD}][${ET_BOARD_TYPE}] restoring clean target directory *****\n\n"
	rm -rf ${TARGET}
	cp -a ${TARGET}-bare ${TARGET}
else
	cp -a ${TARGET} ${TARGET}-bare
fi

# Update target file system
mkdir -p ${TARGET}/lib/firmware
rsync -av ${ET_DIR}/common/rootfs/* ${TARGET}/ 2>/dev/null
if [ -d ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib ]; then
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libssp.so* ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libSegFault.so ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libmemusage.so ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libpcprofile.so ${TARGET}/lib/ 2>/dev/null
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/sysroot/lib/libitm.so* ${TARGET}/lib/ 2>/dev/null
fi
if [ -d ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/debug-root ]; then
	rsync -av ${ET_TOOLCHAIN_DIR}/${ET_CROSS_TUPLE}/debug-root/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_KERNEL_DIR}/boot ]; then
	rsync -av ${ET_KERNEL_DIR}/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_BOOTLOADER_DIR}/boot ]; then
	rsync -av ${ET_BOOTLOADER_DIR}/* ${TARGET}/ 2>/dev/null
fi
if [ -d ${ET_OVERLAY_DIR} ]; then
	rsync -av \
		--exclude 'usr/include' \
		--exclude 'usr/lib/pkgconfig' \
		--exclude 'usr/lib/*.a' \
		${ET_OVERLAY_DIR}/ \
		${TARGET}/ 2>/dev/null
fi
printf "\n%s\n\n" "`cat ${TARGET}/etc/issue`" > ${TARGET}/etc/issue
printf "\n::sysinit:/bin/mount -t debugfs none /sys/kernel/debug\n" >> ${TARGET}/etc/inittab
printf "\n::sysinit:/bin/mount -t configfs none /sys/kernel/config\n" >> ${TARGET}/etc/inittab
sed -i s,::sysinit:/etc/init.d/rcS,#::sysinit:/etc/init.d/rcS, ${TARGET}/etc/inittab
printf "\n::sysinit:/etc/init.d/rcS\n" >> ${TARGET}/etc/inittab
printf "\n#ttyGS0::respawn:/sbin/getty -L ttyGS0 115200 xterm-color\n" >> ${TARGET}/etc/inittab

# Board Specific Modifications
case "${ET_BOARD_TYPE}" in
omap2plus*|sama5d3-xpld*|zynq*|meson*|layerscape*)
	printf "\n***** [${ET_BOARD}][${ET_BOARD_TYPE}] custom modifications *****\n\n"
	# Board Common
	mkdir -p ${TARGET}/media/BOOT
	mkdir -p ${TARGET}/media/rootfs
	sed -i s,ext2,ext4, ${TARGET}/etc/fstab
	echo "${ET_BOARD}" | grep -q "aml-s905x-cc"
	if [ "$?" = "0" ]; then
		# This board's U-Boot places SD on mmc0, Linux places eMMC on mmc0
		printf "/dev/mmcblk1p1 /media/BOOT auto defaults 0 0\n" >> ${TARGET}/etc/fstab
		printf "/dev/mmcblk1p2 /media/rootfs auto defaults 0 0\n" >> ${TARGET}/etc/fstab
	else
		# Everyone else
		printf "/dev/mmcblk0p1 /media/BOOT auto defaults 0 0\n" >> ${TARGET}/etc/fstab
		printf "/dev/mmcblk0p2 /media/rootfs auto defaults 0 0\n" >> ${TARGET}/etc/fstab
	fi
	# Board Firmware
	case "${ET_BOARD}" in
	am335x-pocketbeagle*)
		rsync -av ${ET_DIR}/firmware/am335x* ${TARGET}/lib/firmware/
		;;
	aml-s905x-cc*)
		# Build '/usr/sbin/aml-update' file for on-target updates of SD and eMMC
		printf "#!/bin/bash\n" > ${TARGET}/usr/sbin/aml-update
		printf "dd if=/media/BOOT/u-boot.bin of=/dev/mmcblk0 bs=512 seek=1\n" >> ${TARGET}/usr/sbin/aml-update
		printf "sync\n" >> ${TARGET}/usr/sbin/aml-update
		printf "dd if=/media/BOOT/u-boot.bin.sd.bin of=/dev/mmcblk1 conv=fsync,notrunc bs=1 count=444\n" >> ${TARGET}/usr/sbin/aml-update
		printf "dd if=/media/BOOT/u-boot.bin.sd.bin of=/dev/mmcblk1 conv=fsync,notrunc bs=512 skip=1 seek=1\n" >> ${TARGET}/usr/sbin/aml-update
		printf "sync\n" >> ${TARGET}/usr/sbin/aml-update
		chmod +x ${TARGET}/usr/sbin/aml-update
		;;
	*)
		# DEFAULT NO-OP
		;;
	esac
	# Boards capable of using UBI on NAND
	case "${ET_BOARD}" in
	omap3-beagle*|omap3-evm*|sama5d3-xpld*|ls1043ardb*)
		mkdir -p ${TARGET}/media/ubifs
		printf "ubi0:rootfs /media/ubifs ubifs defaults 0 0\n" >> ${TARGET}/etc/fstab
		;;
	*)
		# DEFAULT NO-OP
		;;
	esac
	# Board with larger, and different, user-space
	case "${ET_BOARD_TYPE}" in
	meson*|layerscape*)
		sed -i s,\#PermitRootLogin\ prohibit-password,PermitRootLogin\ yes, ${TARGET}/etc/ssh/sshd_config
		;;
	*)
		# DEFAULT NO-OP
		;;
	esac
	;;
*)
	# DEFAULT NO-OP
	;;
esac
